# Generated by Django 5.0.4 on 2024-04-25 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matchID', models.CharField(max_length=48)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messageID', models.CharField(max_length=48)),
                ('content', models.CharField(max_length=256)),
                ('authorID', models.CharField(max_length=48)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.CharField(max_length=48)),
                ('username', models.CharField(max_length=16)),
                ('display_name', models.CharField(max_length=16)),
                ('email', models.CharField(max_length=64)),
                ('mfa_token', models.CharField(max_length=32)),
                ('lang', models.CharField(max_length=6)),
                ('avatarID', models.CharField(max_length=68)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
    ]
