# Generated by Django 5.0.4 on 2024-04-30 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationshipID', models.CharField(max_length=48)),
                ('userA', models.CharField(max_length=48)),
                ('userB', models.CharField(max_length=48)),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tokenID', models.CharField(max_length=48)),
                ('token', models.CharField(max_length=256)),
                ('revoked', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='display_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='mfa_token',
        ),
        migrations.AddField(
            model_name='user',
            name='displayName',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='flags',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='mfaToken',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='oauthUid',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatarID',
            field=models.CharField(max_length=68, null=True),
        ),
    ]
