# Generated by Django 5.0.6 on 2024-08-13 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_verificationcode_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mfaToken',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
