# Generated by Django 5.0.6 on 2024-08-13 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_user_mfatoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='oauthUid',
        ),
    ]
