# Generated by Django 5.0.6 on 2024-08-15 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bannerID',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(max_length=280, null=True),
        ),
    ]
