# Generated by Django 5.0.6 on 2024-09-04 15:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_user_bannerid_user_bio"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="authorID",
        ),
        migrations.RemoveField(
            model_name="message",
            name="id",
        ),
        migrations.AddField(
            model_name="message",
            name="createdAt",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="message",
            name="sender",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sent_messages",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="messageID",
            field=models.CharField(
                default="msg_MTcyNTQ2NDcwNDQwOTU2NDg",
                editable=False,
                max_length=48,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.CreateModel(
            name="Conversation",
            fields=[
                (
                    "conversationID",
                    models.CharField(
                        default="conv_MTcyNTQ2NDcwNDQwODY2Mzk",
                        editable=False,
                        max_length=48,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("type", models.CharField(default="private_message", max_length=50)),
                (
                    "participants",
                    models.ManyToManyField(
                        related_name="conversations", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="message",
            name="conversation",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="api.conversation",
            ),
        ),
    ]
