# Generated by Django 5.0.6 on 2024-09-02 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_user_bannerid_user_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='oauthAccountID',
            field=models.TextField(max_length=64, null=True),
        ),
    ]
