# Generated by Django 5.0.6 on 2024-09-12 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0013_remove_message_authorid_remove_message_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="conversation",
            old_name="type",
            new_name="conversationType",
        ),
        migrations.AlterField(
            model_name="conversation",
            name="conversationID",
            field=models.CharField(
                default="conv_MTcyNjE1NTQ1NTk3OTI3NTY",
                editable=False,
                max_length=48,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="messageID",
            field=models.CharField(
                default="msg_MTcyNjE1NTQ1NTk4MDM2Njk",
                editable=False,
                max_length=48,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
