# Generated by Django 5.0.6 on 2024-09-13 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0014_rename_type_conversation_conversationtype_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="relationship",
            name="status",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="conversation",
            name="conversationID",
            field=models.CharField(
                default="conv_MTcyNjIxOTQ4MjUwMDc1MjI",
                editable=False,
                max_length=48,
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="messageID",
            field=models.CharField(
                default="msg_MTcyNjIxOTQ4MjUwMTM2MDQ",
                editable=False,
                max_length=48,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
