# Generated by Django 5.0.6 on 2024-09-13 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0013_user_oauthaccountid"),
        ("api", "0015_relationship_status_and_more"),
    ]

    operations = []
