# Generated by Django 5.0.6 on 2024-09-20 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_merge_20240913_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='conversationID',
            field=models.CharField(default='conv_MTcyNjgyNjUzMTQ0NzY0MTI', editable=False, max_length=48, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='messageID',
            field=models.CharField(default='msg_MTcyNjgyNjUzMTQ0ODEwNDg', editable=False, max_length=48, primary_key=True, serialize=False),
        ),
    ]
