# Generated by Django 5.0.6 on 2024-09-20 10:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_conversation_receipientid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='playerA',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='playerB',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='startedAt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='conversation',
            name='conversationID',
            field=models.CharField(default='conv_MTcyNjgyODA4MjYwODIzNjM', editable=False, max_length=48, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='messageID',
            field=models.CharField(default='msg_MTcyNjgyODA4MjYwOTg4Nzg', editable=False, max_length=48, primary_key=True, serialize=False),
        ),
    ]
