# Generated by Django 5.0.6 on 2024-09-20 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_match_playera_match_playerb_match_startedat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='winnerID',
            field=models.CharField(max_length=48, null=True),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='conversationID',
            field=models.CharField(default='conv_MTcyNjg0MzE5MTk4Mjc1NTY', editable=False, max_length=48, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='messageID',
            field=models.CharField(default='msg_MTcyNjg0MzE5MTk4Mjg2OQ', editable=False, max_length=48, primary_key=True, serialize=False),
        ),
    ]
