# Generated by Django 5.0.6 on 2024-09-23 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_match_winnerid_alter_conversation_conversationid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=48, unique=True)),
                ('matchID', models.CharField(max_length=48)),
                ('userID', models.CharField(max_length=48)),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='flags',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='scores',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='conversationID',
            field=models.CharField(default='conv_MTcyNzA4NzcxODM2ODI4OTA', editable=False, max_length=48, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='match',
            name='finishedAt',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='matchID',
            field=models.CharField(max_length=48, unique=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='messageID',
            field=models.CharField(default='msg_MTcyNzA4NzcxODM2ODY2MzA', editable=False, max_length=48, primary_key=True, serialize=False),
        ),
    ]
