# Generated by Django 5.0.6 on 2024-09-23 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_gametoken_match_flags_match_scores_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='conversationID',
            field=models.CharField(default='', editable=False, max_length=48, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='messageID',
            field=models.CharField(default='', editable=False, max_length=48, primary_key=True, serialize=False),
        ),
    ]
