# Generated by Django 5.0.6 on 2024-10-07 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_alter_user_displayname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersettings',
            name='colorblind',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='theme',
        ),
        migrations.AddField(
            model_name='usersettings',
            name='selectedPaddleSkin',
            field=models.CharField(max_length=24, null=True),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='selectedTerrainSkin',
            field=models.CharField(max_length=24, null=True),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='userID',
            field=models.CharField(max_length=48, unique=True),
        ),
    ]
