# Generated by Django 5.0.6 on 2024-10-07 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_remove_usersettings_selectedterrainskin_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storeitem',
            old_name='description',
            new_name='assetID',
        ),
    ]
