# Generated by Django 5.0.6 on 2024-10-07 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_alter_purchase_itemid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='selectedPaddleSkin',
            field=models.CharField(max_length=48, null=True),
        ),
    ]
