# Generated by Django 5.0.6 on 2024-10-13 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_user_xp'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='messageType',
            field=models.IntegerField(default=0),
        ),
    ]
