# Generated by Django 5.0.6 on 2024-11-04 13:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_match_whitelist_message_messagetype_tournament_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='whitelist',
            field=models.ManyToManyField(related_name='whitelisted_matches', to=settings.AUTH_USER_MODEL),
        ),
    ]
