# Generated by Django 5.0.6 on 2024-10-13 14:51

import api.util
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_message_messagetype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tournamentID', models.CharField(default=api.util.generate_id, max_length=48, unique=True)),
                ('name', models.CharField(max_length=16)),
                ('startDate', models.DateTimeField()),
                ('endDate', models.DateTimeField(default=None, null=True)),
                ('maxParticipants', models.IntegerField(default=8)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ONGOING', 'Ongoing'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('winnerID', models.CharField(default=None, max_length=48, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('isPublic', models.BooleanField(default=True)),
                ('participants', models.ManyToManyField(related_name='tournaments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
