# Generated by Django 5.0.6 on 2024-10-13 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_tournament'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='tournamentID',
            field=models.CharField(max_length=48, unique=True),
        ),
    ]
