# Generated by Django 5.0.6 on 2024-11-08 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_message_inviteid_alter_match_whitelist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='inviteID',
        ),
        migrations.AddField(
            model_name='message',
            name='invite',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='api.tournamentinvite'),
        ),
    ]
