# Generated by Django 5.0.6 on 2024-11-10 21:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_remove_message_inviteid_message_invite'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
