# Generated by Django 5.0.6 on 2024-11-10 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_match_createdat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='startedAt',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
