# Generated by Django 5.0.6 on 2024-10-16 17:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_match_tournament'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='whitelist',
            field=models.ManyToManyField(limit_choices_to=2, related_name='whitelisted_matches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='startDate',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
