# Generated by Django 5.0.6 on 2024-11-12 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_alter_match_startedat_alter_message_content_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='invite',
            new_name='tournamentInvite',
        ),
        migrations.AddField(
            model_name='message',
            name='challengeInvite',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='api.challengeinvite'),
        ),
    ]
