# Generated by Django 5.0.6 on 2024-11-14 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_alter_match_whitelist'),
        ('api', '0037_rename_invite_message_tournamentinvite_and_more'),
    ]

    operations = [
    ]
