# Generated by Django 5.0.6 on 2024-11-15 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_merge_20241114_0911'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GameToken',
        ),
    ]
