import React, { useEffect, useState } from 'react';
import API from '../../../api/api';
import logger from '../../../api/logger';
import OTPInputComponent from '../../Auth/OTPInput';
import { AuthButton, ErrorMessage } from '../../Auth/styles/Authentication.styled';
import { AvailablePlatformsContainer, PlatformButton } from '../../Auth/styles/TwoFactorAuth.styled';
import { GetUser } from '../../../api/user';
import { Backdrop, FormContainer } from '../styles/TwoFactorAuthSecurity.styled';

const TwoFactorAuthSecurity = ({ formData, setUser, setSuccess, setShowTwoFactorAuth }) => {
	const [availablePlatforms, setAvailablePlatforms] = useState([]);
	const [authCode, setAuthCode] = useState('');
	const [disableVerify, setDisableVerify] = useState(true);
	const [error, setError] = useState('');

	useEffect(() => {
		API.get('auth/totp/platform_availability')
			.then(res => {
				setAvailablePlatforms(res.data.available_platforms);
			})
			.catch(err => {
				setError(err.response.data.error);
			});
	}, []);

	const handlePlatform = (platform) => {
		API.post('auth/totp/request', { platform })
			.then(() => {
				logger('2FA: Request sent');
			})
			.catch(err => {
				logger('2FA: Request failed');
				setError(err.response.data.error);
			});
	};

	const handleSubmit = (e) => {
		e.preventDefault();
		setDisableVerify(true);
		setError('');

		const submissionData = { ...formData };

		if (!submissionData.phone_number) {
			delete submissionData.phone_number;
		}

		setDisableVerify(true);
		API.patch('users/@me/profile', { ...submissionData, otp: authCode })
			.then(res => {
				logger('2FA: Success');
				setSuccess('Security updated successfully');
				GetUser()
					.then(res => {
						setUser(res.data);
						logger('User data refetched and updated in context:', res.data);
					})
					.catch(err => {
						setError(err.response.data.error);
						setSuccess('');
					});
				setShowTwoFactorAuth(false);
			})
			.catch(err => {
				setError(err.response.data.error);
				setSuccess('');
			})
			.finally(() => {
				setDisableVerify(false);
			});
	};

	return (
		<>
			<Backdrop/>
			<FormContainer onSubmit={handleSubmit}>
				<h1>Two Factor Authentication</h1>
				<p>Enter the 6-digit code generated by your chosen platform.</p>

				<OTPInputComponent setAuthCode={setAuthCode} setDisableVerify={setDisableVerify}/>

				{error && <ErrorMessage>{error}</ErrorMessage>}

				<AvailablePlatformsContainer>
					{availablePlatforms ? availablePlatforms.filter(platform => platform !== 'app').map((platform) => (
						<PlatformButton
							key={platform}
							type="button"
							onClick={() => handlePlatform(platform)}
						>
							{platform === "email" && <i className="bi bi-envelope-fill"/>}
							{platform === "sms" && <i className="bi bi-chat-left-text-fill"/>}
						</PlatformButton>
					)) : (
						<p>No Available Platforms...</p>
					)}
				</AvailablePlatformsContainer>

				<AuthButton type="submit" disabled={disableVerify}>
					Verify
				</AuthButton>

				<AuthButton type="button" onClick={() => setShowTwoFactorAuth(false)}>
					Back
				</AuthButton>
			</FormContainer>
		</>
	);
};

export default TwoFactorAuthSecurity;
