"""
Constants
"""
WS_URL = 'wss://{}:{}/ws/match'
TIME_BETWEEN_UPDATE_INTERVAL_MS = 1000
MIN_SEND_INTERVAL_MS = 10
FPS_INTERVAL_MS = 16.67 # 60 FPS = 16.67

COURT_WIDTH = 1200
COURT_HEIGHT = 750
BALL_RADIUS = 25
PADDLE_HEIGHT = 120
PADDLE_SPEED = 10
LEFT_SIDE_PADDLE_X = 10
RIGHT_SIDE_PADDLE_X = COURT_WIDTH - LEFT_SIDE_PADDLE_X

REQUIRED_PARAMS = "['type', 'gameID']"
