import React, { useContext, useState } from "react";
import { useNavigate } from "react-router-dom";
import axios from "axios";
import { ApiLogin } from "../../api/auth";
import logger from "../../api/logger";
import { AuthContext } from "../../context/AuthContext";
import {
	AuthenticationSection,
	AuthButton,
	FormContainer,
	Input,
	ErrorMessage
} from "./styles/Authentication.styled";
import { AvailablePlatformsContainer, PlatformButton } from "./styles/TwoFactorAuth.styled";

const TwoFactorAuth = ({ username, password, setIsTwoFactorAuth, availablePlatforms }) => {
	const navigate = useNavigate();
	const { setIsLoggedIn } = useContext(AuthContext);
	const [authCode, setAuthCode] = useState("");
	const [loading, setLoading] = useState(!authCode);
	const [error, setError] = useState("");

	const handleChange = (e) => {
		setAuthCode(e.target.value);
		setLoading(!e.target.value);
	};

	const handlePlatform = (platform) => {
		axios.post('http://localhost:8888/api/v1/auth/totp/request', { username, password, platform })
			.then(() => {
				logger('2FA: Request sent');
			})
			.catch(err => {
				logger('2FA: Request failed');
				console.error(err.response.data.error);
			});
	};

	const handleSubmit = (e) => {
		e.preventDefault();
		setLoading(true);
		setError("");

		ApiLogin(username, password, authCode)
			.then(() => {
				setIsLoggedIn(true);
				navigate("/");
			})
			.catch((err) => {
				console.log('PLSPLDPSLPLFDPSPAFLDSP:',err);
				setError(err.response.data.error);
			});
	  };

	return (
		<AuthenticationSection>
			<FormContainer onSubmit={handleSubmit}>
				<h1>Two Factor Authentication</h1>
				<p>Enter the 6-digit code generated by your authentication app.</p>
				<Input
					type="text"
					id="authCode"
					placeholder="Enter 6-digit authentication code"
					value={authCode}
					onChange={handleChange}
					pattern="[0-9]{6}"
				/>

				{error && <ErrorMessage>{error}</ErrorMessage>}

				<AvailablePlatformsContainer>
					{availablePlatforms ? availablePlatforms.filter(platform => platform !== 'app').map((platform) => (
						<PlatformButton
							key={platform}
							type="button"
							onClick={() => handlePlatform(platform)}
						>
							{platform === "email" && <i className="bi bi-envelope-fill"/>}
							{platform === "sms" && <i className="bi bi-chat-left-text-fill"/>}
						</PlatformButton>
					)) : (
						<p>No Available Platforms...</p>
					)}
				</AvailablePlatformsContainer>

				<AuthButton type="submit" disabled={loading}>
					Verify
				</AuthButton>
				<AuthButton type="AuthButton" onClick={() => setIsTwoFactorAuth(false)}>
					Back
				</AuthButton>
			</FormContainer>
		</AuthenticationSection>
	);
};

export default TwoFactorAuth;
