import React, { useContext, useEffect, useState } from "react";
import API from "../../../../api/api";
import OTPInputComponent from "../../../Auth/OTPInput";
import { Backdrop, FormContainer } from "../../styles/TwoFactorAuth.styled";
import { AvailablePlatformsContainer, PlatformButton } from "../../../Auth/styles/TwoFactorAuth.styled";
import PongButton from "../../../../styles/shared/PongButton.styled";
import ErrorMessage from "../../../../styles/shared/ErrorMessage.styled";
import { RelationContext } from "../../../../context/RelationContext";

const TwoFactorAuthDeactivate = ({ setShow2FA, setShowQRCode, setIs2FAEnabled }) => {
	const [availablePlatforms, setAvailablePlatforms] = useState([]);
	const [authCode, setAuthCode] = useState('');
	const [disableVerify, setDisableVerify] = useState(true);
	const [error, setError] = useState('');
	const { setSendNotification } = useContext(RelationContext);

	useEffect(() => {
		API.get('auth/totp/platform_availability')
			.then(res => {
				setAvailablePlatforms(res.data.available_platforms);
			})
			.catch(err => {
				setSendNotification({ type: 'error', message: `${err?.response?.data?.error || 'An error occurred'}` });
			});
	}, [setSendNotification]);

	const handlePlatform = platform => {
		API.post('auth/totp/request', { platform })
			.then(() => {
				setSendNotification({ type: 'success', message: 'Request sent' });
			})
			.catch(err => {
				setSendNotification({ type: 'error', message: `${err?.response?.data?.error || 'An error occurred'}` });
			});
	}

	const handleSubmit = e => {
		e.preventDefault();
		setDisableVerify(true);
		setError('');

		API.post('auth/totp/delete', { otp: authCode })
			.then(() => {
				setShowQRCode(false);
				setIs2FAEnabled(false);
				setShow2FA(false);
				setError('');
			})
			.catch(err => {
				setError(err?.response?.data?.error || 'An error occurred');
			});
	};

	return (
		<>
			<Backdrop/>
			<FormContainer onSubmit={handleSubmit}>
				<h1>Two Factor Authentication</h1>
				<p>Enter the 6-digit code generated by your chosen platform.</p>

				<OTPInputComponent setAuthCode={setAuthCode} setDisableVerify={setDisableVerify}/>

				{error && <ErrorMessage>{error}</ErrorMessage>}

				<AvailablePlatformsContainer>
					{availablePlatforms ? availablePlatforms.filter(platform => platform !== 'app').map(platform => (
						<PlatformButton
							key={platform}
							type="button"
							onClick={() => handlePlatform(platform)}
						>
							{platform === 'email' && <i className="bi bi-envelope-fill"/>}
							{platform === 'sms' && <i className="bi bi-chat-left-text-fill"/>}
						</PlatformButton>
					)) : (
						<p>No Available Platforms...</p>
					)}
				</AvailablePlatformsContainer>

				<PongButton type="submit" disabled={disableVerify}>
					Verify
				</PongButton>

				<PongButton type="button" onClick={() => setShow2FA(false)}>
					Back
				</PongButton>
			</FormContainer>
		</>
	);
};

export default TwoFactorAuthDeactivate;
